apiVersion: v1
data:
  database.yml: |
    production:
      adapter: postgresql
      encoding: utf8
      database: canvas_production
      host: canvas-postgres

kind: ConfigMap
metadata:
  name: canvas-configmap
  namespace: canvas
