apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: canvas
  namespace: canvas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: canvas
        app: canvas
    spec:
      containers:
      - name: canvas
        image: instructure/canvas-lms:master
        imagePullPolicy: Always
        env:
        - name: CANVAS_LMS_ACCOUNT_NAME
          value: canvas-k8s
        - name: CANVAS_LMS_ADMIN_EMAIL
          value: admin1@example.com
        - name: CANVAS_LMS_ADMIN_PASSWORD
          value: password
        - name: CANVAS_LMS_STATS_COLLECTION
          value: opt_out
        - name: RAILS_DB_HOST
          value: canvas-postgres
      #DOMAIN_URL: canvas-web:8443
      #RAILS_HOST_WITH_PORT: canvas-web:8443
      #S3_ACCESS_KEY: x
      #S3_SECRET_KEY: x

        ports:
        - name: http
          containerPort: 7000
        volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/config
        livenessProbe:
          httpGet:
            path: /health_check
            port: 7000
          initialDelaySeconds: 180
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /health_check
            port: 7000
          initialDelaySeconds: 15
          timeoutSeconds: 1
      volumes:
        - name: config-volume
          configMap:
            name: canvas-configmap
        - name: data
