apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: canvas-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: canvas-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        imagePullPolicy: Always
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
